### ISSUE TITLE
Permission denied for running syz-executor inside QEMU VM?

### ISSUE THREAD

**Issue by docfate111** [SunHao-0/healer#35]
```
$ ./bin/healer -d stretch.img --ssh-key stretch.id_rsa -k bzImage
...
[2021-08-31T22:33:48Z INFO  healer_fuzzer] detecting features
Error: failed to detect features

Caused by:
    detect: '"ssh" "-F" "/dev/null" "-o" "BatchMode=yes" "-o" "IdentitiesOnly=yes" "-o" "StrictHostK.
    bash: /root/syz-executor: Permission denied
```
did i setup something wrong?
I am able to run syzkaller and qemu and ssh in so I think those are working fine?

**Comment by SunHao-0** [comment]
I think the problem here is your `syz-executor` does not have `execution` permission.  Based on your error log, `Healer` has SCP the `syz-executor` executable file to qemu instance. Then, it tries to run `syz-executor check` to detect the features that the current kernel support but failed due to the permission issue. Therefore, my suggestion is to check the file permission on your host (i.e., `ls -l syz-executor`) and make sure you're using the patched syz-executor from `syz-bin`.

**Comment by docfate111** [comment]
oh thanks
now 
```
021-09-01T04:01:31Z INFO  healer_fuzzer] detecting features
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `8`', syz_wrapper/src/exec/features.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SunHao-0** [comment]
I think you are not using the **patched** syz-executor. Healer will execute `syz-executor check` to detect kernel features after QEMU booted. The *check* option is only supported by the patched version, see [here](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/patches/features.h). Here is what you should do, rebuild Healer with `cargo build --release` and copy executable files from **target/release/syz-bin**, all the patched binary files should be there.

**Comment by docfate111** [comment]
Thank you it is working now.
